Feature/accueil
Joubeli/TCH pull request #5
Opened 2022-01-31 21:05 UTC by fatmaGh

2022-02-02 09:32 UTC, Joubeli commented on public/index.html
> +    <link
please remove empty lines

2022-02-02 09:32 UTC, Joubeli commented on public/index.html
>      <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
good you specify a significant name for logo ( for example logo_TCH)

2022-02-02 09:54 UTC, Joubeli requested changes

2022-02-02 09:54 UTC, Joubeli commented on src/App.css
> +.button:hover,
if we don't use the hover definition in UI please remove it

2022-02-02 09:54 UTC, Joubeli commented on src/App.css
> -  left: calc(50% - 60px);
please remove empty lines

2022-02-02 09:54 UTC, Joubeli commented on src/components/Accueil/Accueil.js
> +      <section id='accueil' style={{height: '500px', paddingTop:'90px'}}>
it's better to specify all style things in App.css

2022-02-02 09:54 UTC, Joubeli commented on package.json
> +    "emailjs-com": "^3.2.0",
if we don't use email js plugin please remove it

2022-02-02 09:54 UTC, Joubeli commented on src/components/Apropos/Apropos.css
> +.sec-apropos {
please rename the file name to A_Propos,

2022-02-02 09:54 UTC, Joubeli commented on src/components/Apropos/Apropos.css
> +    /* box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px; */
please remove dead code

2022-02-02 09:54 UTC, Joubeli commented on src/components/Apropos/Apropos.css
> +
please remove empty lines

2022-02-02 09:54 UTC, Joubeli commented on src/components/Contact/Contact.js
> +
please remove empty lines

2022-02-02 09:54 UTC, Joubeli commented on src/components/Contact/Contact.js
> +
remove all empty lines

2022-02-02 09:54 UTC, Joubeli commented on src/components/Contact/Contact.js
> +                <svg style={{marginTop:'25px',marginLeft:'8%'}} xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path fill="#459baa" d="M12 0c-4.198 0-8 3.403-8 7.602 0
is it necessary to use d parameters !

2022-02-02 09:54 UTC, Joubeli commented on src/components/Contact/Contact.js
> +          </div>
could you install vs prettier extension, it will refine the code overview

2022-02-02 09:54 UTC, Joubeli commented on src/components/Footer/Footer.css
> +
empty lines 👍 I will not precise this comment again please take care of empty lines 💯

2022-02-02 09:54 UTC, Joubeli commented on src/components/Footer/Footer.js
> +            {/* <svg className='arrow' xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path fill='#459baa' d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-1
please remove dead code !

2022-02-02 09:54 UTC, Joubeli commented on src/components/Partenaires/Partenaires.css
> +    /* height: 100px;
remove dead code

2022-02-02 09:54 UTC, Joubeli commented on src/components/Produits/Produits.js
> +          </Carousel>
remove all unneeded lines

2022-02-02 09:54 UTC, Joubeli commented on src/components/Produits/Produits.js
> +                    <img src="https://media.istockphoto.com/photos/joining-electrical-wires-with-twisting-wire-nuts-picture-id1184331655?k=20&m=1184331655&s=612x612&w=0&h=1CmdJvPkikdqqUpjsNehvVsOwD8f
I think it's better to centralized all images in just one folder and call them directly from that folder, it's not a best practice to add src strings inside the code ( can you go through all src variables and replace them with a callable parameters)

2022-02-06 09:32 UTC, fatmaGh commented on src/App.css
> +.button:hover,
Done

2022-02-06 09:36 UTC, fatmaGh commented on public/index.html
> +    <link
Done

2022-02-06 09:38 UTC, fatmaGh commented on public/index.html
>      <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
This is the old react icon and i removed it

2022-02-06 09:38 UTC, fatmaGh commented on src/App.css
> -  left: calc(50% - 60px);
Done

2022-02-06 09:39 UTC, fatmaGh commented on src/components/Accueil/Accueil.js
> +      <section id='accueil' style={{height: '500px', paddingTop:'90px'}}>
Done in all files of this branche

2022-02-06 09:39 UTC, fatmaGh commented on package.json
> +    "emailjs-com": "^3.2.0",
Done, also for all other unused packages

2022-02-06 09:40 UTC, fatmaGh commented on src/components/Apropos/Apropos.css
> +.sec-apropos {
Done

2022-02-06 09:40 UTC, fatmaGh commented on src/components/Apropos/Apropos.css
> +    /* box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px; */
Done

2022-02-06 09:40 UTC, fatmaGh commented on src/components/Apropos/Apropos.css
> +
Done

2022-02-06 09:40 UTC, fatmaGh commented on src/components/Contact/Contact.js
> +
Done

2022-02-06 09:41 UTC, fatmaGh commented on src/components/Contact/Contact.js
> +
Done

2022-02-06 09:43 UTC, fatmaGh commented on src/components/Contact/Contact.js
> +          </div>
I already have it and i did format the code for all the files in this branch

2022-02-06 09:44 UTC, fatmaGh commented on src/components/Produits/Produits.js
> +                    <img src="https://media.istockphoto.com/photos/joining-electrical-wires-with-twisting-wire-nuts-picture-id1184331655?k=20&m=1184331655&s=612x612&w=0&h=1CmdJvPkikdqqUpjsNehvVsOwD8f
Done, also for all social media icons and arrow icons

2022-02-06 09:53 UTC, merged